version: "3.7"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/__pycache__
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
      - "3010:3010"
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kosciuszkon
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

    

volumes:
  static:
  frontend: